pipeline {
    agent any

    environment {
        PYSPARK_PYTHON = "/usr/bin/python3"
        PYSPARK_DRIVER_PYTHON = "/usr/bin/python3"
    }

    stages {
        stage('Upgrade pip') {
            steps {
                sh '''
                    python3 -m pip install --upgrade pip setuptools wheel
                '''
            }
        }

        stage('Install Python dependencies') {
            steps {
                sh '''
                    python3 -m pip install --user -r TFL_Streaming/requirements.txt
                '''
            }
        }

        stage('Run Producer (1 min)') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    sh '''
                        spark-submit \
                          --master local \
                          --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.7","com.lihaoyi:requests_2.11:0.7.1" \
                          TFL_Streaming/src/producer.py
                    '''
                }
            }
        }

        stage('Run Consumer (1 min)') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    sh '''
                        spark-submit \
                          --master local \
                          --packages "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.7" \
                          TFL_Streaming/src/consumer.py
                    '''
                }
            }
        }

        stage('Refresh Impala Metadata') {
            steps {
                sh '''
                    impala-shell -q "REFRESH streaming_tfl_db.tfl_streaming_arrivals;"
                '''
            }
        }
    }
}
