pipeline {
    agent any

    environment {
        PYSPARK_PYTHON = "/usr/bin/python3"
        PYSPARK_DRIVER_PYTHON = "/usr/bin/python3"
    }

    stages {

        stage('Upgrade pip') {
            steps {
                sh '''
                    python3 -m pip install --upgrade pip setuptools wheel
                '''
            }
        }

        // --------------------------------------------------
        // Disabled API Extraction Stage
        // --------------------------------------------------
        // stage('1. Data Extraction from API') {
        //     steps {
        //         echo "Running API data extraction (3 cycles)..."
        //         sh 'python3 TFL_Batch_Processing/src/bronze/rawdataextraction.py'
        //     }
        // }
        // --------------------------------------------------

        stage('Run Silver Transformations') {
            steps {
                echo "Running Silver layer transformations..."
                sh 'python3 TFL_Batch_Processing/src/silver/Transformations.py'
            }
        }

    }
}

